server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: Naman@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true